import r2wc from '@r2wc/react-to-web-component';
import ChatWidget from './chat';

customElements.define('journey-builder-chat', r2wc(ChatWidget, {
    shadow: "closed",
    props: {
        api_key: "string",
        output_type: "string",
        input_type: "string",
        output_component: "string",
        chat_trigger_style: "json",
        host_url: "string",
        flow_id: "string",
        tweaks:"json",
        send_icon_style:"json",
        bot_message_style:"json",
        user_message_style:"json",
        chat_window_style:"json",
        height:"string",
        width:"string",
        error_message_style:"json",
        send_button_style:"json",
        online: "boolean",
        online_message: "string",
        offline_message: "string",
        window_title: "string",
        chat_position:"string",
        placeholder:"string",
        input_style:"json",
        placeholder_sending:"string",
        input_container_style:"json",
        additional_headers:"json",
        session_id:"string",
        start_open: "boolean",
        remove_file_btn_style: "json",
        attach_img_style: "json",
        attached_img_grid_style: "json",
        allow_img_expand:"boolean",
        attached_img_style: "json",
        attach_file_style: "json",
        attach_img_button_style: "json",
        img_modal_overlay_style: "json",
        img_modal_img_style: "json",
        files_preview_container_style: "json",
        header_chat_style: "json",
        header_subtitle_style: "json",
        show_chat_status: "boolean",
        attached_file_style: "json",
        error_send_text_file_style: "json",
        retry_send_file_btn_style: "json",
        allow_to_send_imgs:"boolean",
        allow_web_hook: "boolean",
    }
}));